_wandb:
    value:
        cli_version: 0.22.2
        e:
            5b92p2cohk2qk6jtsbc3p405j3kw1ci7:
                codePath: 04_ICU_ML_W&B.ipynb
                codePathLocal: 04_ICU_ML_W&B.ipynb
                cpu_count: 16
                cpu_count_logical: 22
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1021821579264"
                        used: "276494434304"
                email: idiazl@faculty.ie.edu
                executable: c:\Users\idiaz\miniconda3\envs\icu-survival\python.exe
                git:
                    commit: ebb8e1e77d6675576becf39809913f6c7608e906
                    remote: https://github.com/IE-ML-for-Healthcare/ICU_Survival_analysis.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-c8cc09aa-1864-aad2-d166-fe5d44ecf25d
                host: IvanDiaz
                memory:
                    total: "33752997888"
                os: Windows-10-10.0.26200-SP0
                program: c:\Users\idiaz\OneDrive - IE University\00. IE Courses\01. 2025_H2\1. ML4HC\ICU_Survival_analysis\04_ICU_ML_W&B.ipynb
                python: CPython 3.11.14
                root: c:\Users\idiaz\OneDrive - IE University\00. IE Courses\01. 2025_H2\1. ML4HC\ICU_Survival_analysis
                startedAt: "2025-10-30T13:00:22.896928Z"
                writerId: 5b92p2cohk2qk6jtsbc3p405j3kw1ci7
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
                - 14
                - 16
            "4": 3.11.14
            "5": 0.22.2
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.22.2
            "13": windows-amd64
        visualize:
            pr_curve_test_final:
                panel_config:
                    fieldSettings:
                        class: class
                        x: recall
                        "y": precision
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Precision-Recall Curve
                        x-axis-title: Recall
                        y-axis-title: Precision
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: pr_curve_test_final_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            roc_curve_test_final:
                panel_config:
                    fieldSettings:
                        class: class
                        x: fpr
                        "y": tpr
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: ROC Curve
                        x-axis-title: False positive rate
                        y-axis-title: True positive rate
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: roc_curve_test_final_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
class_weight:
    value: balanced
max_depth:
    value: 16
max_features:
    value: sqrt
min_samples_leaf:
    value: 10
n_estimators:
    value: 500
