_wandb:
    value:
        cli_version: 0.22.2
        e:
            h0ffqtpa9aogz54x63t16qc6ikxkazh5:
                codePath: 04_ICU_ML_LR_DT_RF.ipynb
                codePathLocal: 04_ICU_ML_LR_DT_RF.ipynb
                email: idiazl@faculty.ie.edu
                executable: c:\Users\idiaz\miniconda3\envs\icu-survival\python.exe
                git:
                    commit: 96043d7f4950bad383202e5223d7e71ecd3782fa
                    remote: https://github.com/IE-ML-for-Healthcare/ICU_Survival_analysis.git
                host: IvanDiaz
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\idiaz\OneDrive - IE University\00. IE Courses\01. 2025_H2\1. ML4HC\ICU_Survival_analysis\04_ICU_ML_LR_DT_RF.ipynb
                python: CPython 3.11.14
                root: c:\Users\idiaz\OneDrive - IE University\00. IE Courses\01. 2025_H2\1. ML4HC\ICU_Survival_analysis
                startedAt: "2025-10-23T08:42:44.510778Z"
                writerId: h0ffqtpa9aogz54x63t16qc6ikxkazh5
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
            "4": 3.11.14
            "5": 0.22.2
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.22.2
            "13": windows-amd64
