_wandb:
    value:
        cli_version: 0.22.2
        e:
            0sh9cjdrlu8vbjrnznmuk1cbbrb65b92:
                codePath: 04_ICU_ML_W&B - Copy.ipynb
                codePathLocal: 04_ICU_ML_W&B - Copy.ipynb
                email: idiazl@faculty.ie.edu
                executable: c:\Users\idiaz\miniconda3\envs\icu-survival\python.exe
                git:
                    commit: 7f62a38ea5f4d36d699cf95dd9956b64c56975d7
                    remote: https://github.com/IE-ML-for-Healthcare/ICU_Survival_analysis.git
                host: IvanDiaz
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\idiaz\OneDrive - IE University\00. IE Courses\01. 2025_H2\1. ML4HC\ICU_Survival_analysis\04_ICU_ML_W&B - Copy.ipynb
                python: CPython 3.11.14
                root: c:\Users\idiaz\OneDrive - IE University\00. IE Courses\01. 2025_H2\1. ML4HC\ICU_Survival_analysis
                startedAt: "2025-10-23T12:40:58.867496Z"
                writerId: 0sh9cjdrlu8vbjrnznmuk1cbbrb65b92
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.11.14
            "5": 0.22.2
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.22.2
            "13": windows-amd64
max_depth:
    value: 16
max_features:
    value: sqrt
min_samples_leaf:
    value: 10
n_estimators:
    value: 300
