_wandb:
    value:
        cli_version: 0.22.2
        e:
            935dcmcqe8qxvygzuerv39f3nya0wals:
                codePath: 04_ICU_ML_LR_DT_RF.ipynb
                codePathLocal: 04_ICU_ML_LR_DT_RF.ipynb
                cpu_count: 16
                cpu_count_logical: 22
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1021821579264"
                        used: "274032443392"
                email: idiazl@faculty.ie.edu
                executable: c:\Users\idiaz\miniconda3\envs\icu-survival\python.exe
                git:
                    commit: abccaefa98e94ee2bd49b572c8377c6b9d8c22f3
                    remote: https://github.com/IE-ML-for-Healthcare/ICU_Survival_analysis.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-c8cc09aa-1864-aad2-d166-fe5d44ecf25d
                host: IvanDiaz
                memory:
                    total: "33752997888"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\idiaz\OneDrive - IE University\00. IE Courses\01. 2025_H2\1. ML4HC\ICU_Survival_analysis\04_ICU_ML_LR_DT_RF.ipynb
                python: CPython 3.11.14
                root: c:\Users\idiaz\OneDrive - IE University\00. IE Courses\01. 2025_H2\1. ML4HC\ICU_Survival_analysis
                startedAt: "2025-10-22T20:49:28.967109Z"
                writerId: 935dcmcqe8qxvygzuerv39f3nya0wals
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.11.14
            "5": 0.22.2
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.22.2
            "13": windows-amd64
max_depth:
    value: 12
max_features:
    value: sqrt
min_samples_leaf:
    value: 10
n_estimators:
    value: 300
