_wandb:
    value:
        cli_version: 0.22.2
        e:
            vizxaigjxicjbcw8lfud6jnd1hjrlarw:
                codePath: 04_ICU_ML_LR_DT_RF.ipynb
                codePathLocal: 04_ICU_ML_LR_DT_RF.ipynb
                email: idiazl@faculty.ie.edu
                executable: c:\Users\idiaz\miniconda3\envs\icu-survival\python.exe
                git:
                    commit: 7d2648bc333f2c4af665ee02ea12c0ddb09175bf
                    remote: https://github.com/IE-ML-for-Healthcare/ICU_Survival_analysis.git
                host: IvanDiaz
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\idiaz\OneDrive - IE University\00. IE Courses\01. 2025_H2\1. ML4HC\ICU_Survival_analysis\04_ICU_ML_LR_DT_RF.ipynb
                python: CPython 3.11.14
                root: c:\Users\idiaz\OneDrive - IE University\00. IE Courses\01. 2025_H2\1. ML4HC\ICU_Survival_analysis
                startedAt: "2025-10-22T20:03:50.343072Z"
                writerId: vizxaigjxicjbcw8lfud6jnd1hjrlarw
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 14
                - 16
                - 62
            "4": 3.11.14
            "5": 0.22.2
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.22.2
            "13": windows-amd64
documentation:
    value: model_card
max_depth:
    value: 16
max_features:
    value: sqrt
min_samples_leaf:
    value: 5
model_type:
    value: random_forest
n_estimators:
    value: 500
